[build.environment]
  NETLIFY_BUILD_DEBUG = "true"

[build]
  # Default build settings for all branches
  command = "yarn build"
  publish = "dist"

# build for NextJS branch
[context."nextjs"]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  # Currently only applicable for CRA on main
  command = "yarn build"
  publish = "dist"
