name: CI

on:
  # build on PR creation/updates, also when pushing to main/develop, or create a release
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
    tags: [v*]


env:
  REPO_NAME_SLUG: pastelle-ui
  PR_NUMBER: ${{ github.event.number }}
  # INFURA
  NEXT_PUBLIC_INFURA_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_KEY }}
  # IMAGEKIT CDN
  NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY }}
  NEXT_PUBLIC_IMAGEKIT_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_IMAGEKIT_PRIVATE_KEY }}
  NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT }}
  # SHOPIFY
  NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN: ${{ secrets.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN }}
  NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN: ${{ secrets.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN }}
  NEXT_PUBLIC_SHOPIFY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SHOPIFY_API_VERSION }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Yarn PnP Setup
        uses: Araxeus/setup-yarn-pnp-action@v1
            
  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Yarn PnP Setup
        uses: Araxeus/setup-yarn-pnp-action@v1

      - name: Unit Test
        run: yarn test

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Yarn PnP Setup
        uses: Araxeus/setup-yarn-pnp-action@v1

      - name: Run linters
        run: yarn lint

      - name: Commit lint changes
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore: linting"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
        
  
  build:
    name: Build
    needs: [setup,test,lint]
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: yarn build && yarn sitemap:generate

      - name: Commit sitemap
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore: sitemap update"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
